language: node_js
node_js:
  - "13"
dist: trusty
os: linux

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - ng lint
  - ng build --prod --base-href https://jklewa.github.io/data-with-babish-example/
deploy:
  strategy: git
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
